import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import * as f from '../dist/finance.js';
let d=f.sampleData();
f.validateMonths(f.parseCSV(f.csv(d.months)));f.validateInvoices(f.parseCSV(f.csv(d.invoices)),d.months);
for(const month of d.months)for(const mode of ['month','ytd']){const v=f.calculate(d,month.month,mode);assert.ok(Math.abs(v.balance_check)<1);assert.ok(Math.abs(v.cash_check)<1);assert.equal(v.net_income,v.revenue-v.cogs-v.opex-v.depreciation-v.interest-v.income_tax);}
const before=f.calculate(d,'2026-09');f.recordPayment(d,'INV-2026001',10000);const after=f.calculate(d,'2026-09');assert.equal(after.cash-before.cash,10000);assert.equal(before.ar-after.ar,10000);assert.equal(after.net_income,before.net_income);assert.throws(()=>f.recordPayment(d,'INV-2026001',1e9));
f.recordPayment(d,'BILL-2026001',10000);f.validateMonths(d.months);f.validateInvoices(d.invoices,d.months);
for(const kind of ['receivable','payable']){f.addInvoice(d,{id:kind,kind,party:'Example',amount:1000,issued:'2026-09-10',due:'2026-10-10'});f.validateMonths(d.months);f.validateInvoices(d.invoices,d.months);}
const invalid=structuredClone(d.months);invalid[3].equity+=10;assert.throws(()=>f.validateMonths(invalid));assert.throws(()=>f.parseCSV('a,b\n"unclosed,2'));assert.throws(()=>f.validateMonths([d.months[0],d.months[2]]));assert.throws(()=>f.validateInvoices([],d.months));
const noLedger=structuredClone(d);noLedger.ledgerMatched=false;assert.equal(f.calculate(noLedger,'2026-09').overdue_ar,null);
assert.deepEqual(f.forecast(d,d.scenario).map(x=>x.month),['2026-10','2026-11','2026-12']);const z=structuredClone(d);Object.assign(z.months.at(-1),{revenue:0,cogs:0,interest:0,headcount:0,customers:0,new_customers:0});const zv=f.calculate(z,'2026-09');for(const k of ['gross_margin','dso','dpo','revenue_employee','revenue_customer','cac'])assert.equal(zv[k],null);
const html=fs.readFileSync('dist/index.html','utf8');const js=fs.readFileSync('dist/app.js','utf8');const dom=new JSDOM(html,{url:'http://localhost/#overview',runScripts:'outside-only'});const w=dom.window;Object.assign(w,f);let downloads=[],tools=[];w.URL.createObjectURL=blob=>{downloads.push(blob);return 'blob:test';};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};w.scrollTo=()=>{};w.print=()=>{};w.document.modelContext={registerTool:tool=>tools.push(tool)};w.eval(js.replace(/^import[^\n]+\n/,'')+'\nwindow.__test={render,go,handleAction,submit,answer,current,latest,metricModal,close,commitImport,getData:()=>data,setData:x=>{data=x},setPeriod:x=>{period=x},setMode:x=>{mode=x},reportRows};');const t=w.__test;
function click(action,attrs={}){t.handleAction(action,{dataset:{action,...attrs}});}
for(const route of ['overview','statements','cashflow','receivables','payables','budgets','kpis','insights','assistant','reports','data']){w.history.replaceState({},'','#'+route);t.render();assert.ok(w.document.querySelector('h1').textContent);assert.ok(!w.document.querySelector('#content').textContent.includes('undefined'));}
for(const m of f.metrics){t.metricModal(m.id);assert.ok(w.document.querySelector('#modal-title').textContent);t.close();}
for(const id of ['income','balance','cash']){w.history.replaceState({},'','#statements');click('statement',{id});assert.ok(w.document.querySelector('table'));}
for(const id of ['management','income','balance','cash']){w.history.replaceState({},'','#reports');click('report-type',{id});click('save-report');click('export-report');}
for(const act of ['export-view','export-forecast','export-tasks','backup','template-months','template-ledger','export-audit'])click(act);
click('export-ledger',{kind:'receivable'});click('export-invoice',{id:'INV-2026001'});click('export-metric',{id:'revenue'});click('invoice',{id:'INV-2026001'});assert.ok(w.document.querySelector('.modal').textContent.includes('Al Noor'));t.close();
click('payment',{id:'INV-2026001'});const pf=w.document.querySelector('#payment-form');pf.elements.amount.value='1000';const cash0=t.latest().cash;await t.submit(pf);assert.equal(t.latest().cash,cash0+1000);
click('add-invoice',{kind:'receivable'});const af=w.document.querySelector('#invoice-form');af.elements.party.value='New customer';af.elements.amount.value='2000';await t.submit(af);assert.equal(t.latest().ar,f.sampleData().months.at(-1).ar+1000);
f.validateMonths(t.getData().months);f.validateInvoices(t.getData().invoices,t.getData().months);
w.history.replaceState({},'','#budgets');t.render();const bf=w.document.querySelector('#budget-form');bf.elements.budget_revenue.value='900000';await t.submit(bf);assert.equal(t.getData().months.at(-1).budget_revenue,900000);const sf=w.document.querySelector('#scenario-form');sf.elements.growth.value='10';await t.submit(sf);click('save-scenario');assert.equal(t.getData().scenario.growth,10);click('reset-scenario');
click('settings');const settings=w.document.querySelector('#settings-form');settings.elements.company.value='<img onerror=alert(1)> SME';await t.submit(settings);assert.ok(!w.document.querySelector('.company img'));assert.ok(w.document.querySelector('.company').textContent.includes('<img'));
for(const q of ['summary','cash flow','overdue invoices','forecast','Why did expenses increase?','current ratio','gibberish'])assert.ok(t.answer(q).length>20);
click('search');assert.ok(w.document.querySelector('#global-search'));t.close();click('column-guide');t.close();click('add-task',{id:'collections'});assert.equal(t.getData().tasks.length,1);
// Import validation uses the same submit handler and review/commit path as file selection.
const realFD=w.FormData;for(const type of ['months','ledger','restore']){click(type==='restore'?'restore':type==='months'?'import-months':'import-ledger');const dataNow=t.getData();const text=type==='months'?f.csv(f.sampleData().months):type==='ledger'?f.csv(f.sampleData().invoices):JSON.stringify(dataNow);w.FormData=class{get(key){return key==='file'?{size:text.length,name:'test.'+(type==='restore'?'json':'csv'),text:async()=>text}:null;}};await t.submit(w.document.querySelector('#import-form'));assert.ok(w.document.querySelector('#modal-title').textContent.includes('Review'),w.document.querySelector('.modal').textContent);click('confirm-import');w.FormData=realFD;}
assert.equal(tools.length,3);assert.throws(()=>tools[0].execute({metricIds:['bogus']}));assert.equal(tools[0].execute({metricIds:['revenue']}).metrics.length,1);assert.throws(()=>tools[1].execute({section:'bogus'}));assert.equal(tools[1].execute({section:'cashflow'}).section,'cashflow');assert.throws(()=>tools[2].execute({growth:999,cost:2,collectionDays:30}));assert.equal(tools[2].execute({growth:5,cost:2,collectionDays:30}).forecast.length,3);
assert.ok(downloads.length>=12);console.log(JSON.stringify({financialMetrics:f.metrics.length,routes:11,checks:'Reconciliation, ratio edge cases, postings, CSV validation, 54 KPI dialogs, forms, exports, imports, backups, query assistant, navigation and WebMCP handler contracts passed',downloads:downloads.length,liveBrowserOrWebMCPContext:false}));w.close();
